### PR TITLE
pallet-contracts bringup

### PR DESCRIPTION
**Pull request by shamb0**
Integration of pallet-contracts

Fixes : https://github.com/NodleCode/chain/issues/78

### CODE REVIEW

**Comment by shamb0** [comment]
Hello @ETeissonniere,

Integrated `pallet-contracts`, was able to deploy erc20 ink! wasm contract.



But unable to make call to `message` functions. Hit with below error



Quick check, are below versions compatible ? 

| Comp | Ver |
| --- | --- |
| Nodle Chain Node | v2.0.0 |
| api | v4.1.2-6 |
| apps | v0.84.2-9 |

**Comment by ETeissonniere** [comment]
Hi @shamb0! I think Polkadot JS has had some breaking changes recently. Can you try with our fork on nodleprotocol.io instead?

**Comment by shamb0** [comment]
Hello @ETeissonniere,

Great, thanks for quick support.

Quite interesting, with `https://nodleprotocol.io/` able to upload the wasm file, but deployment is failing.





Any suggestions ?

**Comment by shamb0** [comment]
Hello @ETeissonniere,

Sorry for this noob question,

Just want to try out with increased balance.

Looks like accounts are to have low balance.



Had a quick walk on file `chain_spec.rs, main.json`. Looks like no straight forward.

**Comment by ETeissonniere** [comment]
Hey @shamb0, yeah the dev chain shows up with lower balances due to some decimal thingy (our chain uses 12 decimals instead of the 18 that Polkadot js expects). You can bump it in the `chain_spec.rs` if necessary.

**Comment by shamb0** [comment]
Hello @ETeissonniere,

Cool, thanks for pointer.

Increased account balance by modifying the `ENDOWMENT` like below

```rust
    // const ENDOWMENT: Balance = 100 * NODL;
	const ENDOWMENT: Balance = 10_000_000 * DOLLARS;
```



Able to deploy the ERC20 smart contract. but still `message()`  call failing with below error.



Looks like, something is missing in integration.
below new fragment  `pallet_contracts_rpc_runtime_api::ContractsApi()` is going bad.

**Comment by ETeissonniere** [comment]
You need to add the rpc calls to the node too. We have ours in the `rpc.rs` file

**Comment by shamb0** [comment]
Nice, thanks for great support.

Its working now, Sanity check done with erc20 ink! Example.

https://raw.githubusercontent.com/paritytech/ink/master/examples/erc20/lib.rs

**Comment by ETeissonniere** [comment]
Congrats! Let's wait for CI tests to go through and merge then :). Thanks a lot for this.

**Comment by shamb0** [comment]
No problem, thanks a lot. Really enjoyed it :+1:

**Pull request merged**
